types_by_code: dict[int, str] = {
    0x16: 'GET TLS HANDSHAKE',
    0x20: 'MCU_GET_IMAGE',
    0x32: 'MCU_SWITCH_TO_FDT_DOWN',
    0x34: 'MCU_SWITCH_TO_FDT_UP',
    0x36: 'MCU_SWITCH_TO_FDT_MODE MANUAL',
    0x50: 'SETMODE: NAV',
    0x70: 'MCU_SWITCH_TO_IDLE_MODE',
    0x82: 'READ_SENSOR_REGISTER',
    0x98: 'SEND DAC',
    0xA0: 'HEADER',
    0xA2: 'RESET',
    0xA6: 'READ_OTP',
    0xA8: 'FIRMWARE_VERSION',
    0xAE: 'QUERY_MCU_STATE',
    0xB0: 'ACK',
    0xE4: 'PSK HASH',
}
